default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inst_clon2_development

test:
  <<: *default
  database: inst_clon2_test

production:
  <<: *default
  database: inst_clon2_production
  username: inst_clon2
  password: <%= ENV['INST_CLON2_DATABASE_PASSWORD'] %>
